"""
silent_vlog_maker.audit_report — Full markdown + JSON audit report writer.

把 audit + scene + frame description 全部組成 1 個 markdown 文件 + 1 個 JSON。
給用戶 review + 給 build script 當 ground truth。
"""
import json
from pathlib import Path

from .audit import ClipAudit
from .scene_audit import Scene
from .frame_audit import FrameDescription


# ─────────────────────────────────────────────────────────────────────
# Markdown report (human-readable)
# ─────────────────────────────────────────────────────────────────────

def write_markdown_report(
    audits: list[ClipAudit],
    scenes: list[Scene],
    output_path: Path,
    descriptions: dict[str, FrameDescription] = None,
    grid_paths: list[Path] = None,
    project_name: str = "Video Project",
) -> Path:
    """Write comprehensive markdown audit report grouped by scene."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    descriptions = descriptions or {}
    grid_paths = grid_paths or []

    lines = []
    lines.append(f"# Audit Report — {project_name}")
    lines.append("")
    lines.append(f"> Generated by `silent_vlog_maker.audit_report` v2 (R1 11 維度 + M12 scene cluster + M9/M34 hi-res frame audit)")
    lines.append("")

    # ─── 1. Summary stats ───
    total_size = sum(a.file_size_mb for a in audits)
    total_dur = sum(a.duration_sec for a in audits)
    any_hdr = any(a.is_hdr for a in audits)
    any_portrait = any(a.is_portrait for a in audits)
    gps_count = sum(1 for a in audits if a.has_gps)
    cameras = {a.camera_model for a in audits if a.camera_model}
    dates = sorted({a.creation_date_local for a in audits if a.creation_date_local})

    lines.append("## 📊 Summary")
    lines.append("")
    lines.append(f"- Total clips: **{len(audits)}**")
    lines.append(f"- Total footage: **{total_dur:.1f}s** ({total_dur / 60:.1f} min)")
    lines.append(f"- Total size: **{total_size:.1f} MB**")
    lines.append(f"- Scenes: **{len(scenes)}**")
    lines.append(f"- Dates covered: {', '.join(dates) if dates else 'unknown'}")
    lines.append(f"- HDR: {'⚠️ YES — need R10 tonemap' if any_hdr else '✅ All SDR'}")
    lines.append(f"- Orientation: {'📱 portrait detected' if any_portrait else '🖥️ landscape only'}")
    lines.append(f"- GPS: {gps_count}/{len(audits)} clips ({100 * gps_count // max(len(audits), 1)}%)")
    lines.append(f"- Cameras: {', '.join(cameras) if cameras else 'unknown'}")
    lines.append("")

    # ─── 2. Frame audit grids（reference for caption matching M9/M34）───
    if grid_paths:
        lines.append("## 🖼️ Hi-Res Frame Grids（4 frames per clip — Read these BEFORE writing caption！）")
        lines.append("")
        lines.append("> M9/M34 mandatory：每張 caption 寫之前先 Read 這些 grid 確認實拍內容對應。")
        lines.append("")
        for p in grid_paths:
            lines.append(f"- `{p.name}` — Read me to verify clip content")
        lines.append("")

    # ─── 3. Scene timeline ───
    lines.append("## 🕐 Scene Timeline（chronological + GPS-clustered）")
    lines.append("")
    for s in scenes:
        time_range = ""
        if s.start_time_iso and s.end_time_iso:
            time_range = f"{s.start_time_iso[11:16]}–{s.end_time_iso[11:16]}"
        period = s.period or ""
        label = f" — **{s.location_label}**" if s.location_label else ""
        map_link = f" [📍 map]({s.google_maps_url})" if s.google_maps_url else ""

        lines.append(f"### Scene {s.scene_id}: {s.date_local} {period} {time_range}{label}{map_link}")
        lines.append("")
        lines.append(f"- {s.num_clips} clips / {s.duration_sec:.0f}s footage / span {s.span_min:.1f} min")
        if s.center_lat:
            lines.append(f"- GPS center: ({s.center_lat:.4f}, {s.center_lng:.4f})")
        lines.append("")
        lines.append("| Time | Clip | Duration | Description |")
        lines.append("|---|---|---|---|")
        for c in s.clips:
            t = c.creation_time_local or "??:??"
            desc = ""
            if c.filename in descriptions:
                d = descriptions[c.filename]
                desc = d.description
                if d.text_visible:
                    desc += f" / 招牌字: {', '.join(d.text_visible)}"
            lines.append(f"| {t} | `{c.filename}` | {c.duration_sec:.1f}s | {desc or '_(待補 — Read grid 寫描述)_'} |")
        lines.append("")

    # ─── 4. Detailed per-clip table ───
    lines.append("## 📋 Per-clip Detail (R1 11 維度)")
    lines.append("")
    lines.append("| Clip | Codec | Res | fps | rot | HDR | Dur | Local time | GPS | Camera |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for a in audits:
        hdr_flag = "HDR" if a.is_hdr else ""
        gps_flag = f"({a.gps_lat:.4f},{a.gps_lng:.4f})" if a.has_gps else "—"
        cam = a.camera_model or "—"
        lines.append(
            f"| `{a.filename}` | {a.codec} | {a.width}×{a.height} | {a.fps:.0f} "
            f"| {a.rotation} | {hdr_flag} | {a.duration_sec:.1f}s "
            f"| {a.creation_time_local or 'N/A'} | {gps_flag} | {cam} |"
        )
    lines.append("")

    # ─── 5. Suggested cut-plan structure ───
    lines.append("## 💡 Suggested Cut-Plan Skeleton")
    lines.append("")
    lines.append("Based on chronological scene clusters → narrative arc:")
    lines.append("")
    for i, s in enumerate(scenes):
        period = s.period or ""
        label = s.location_label or f"場景 {s.scene_id}"
        lines.append(f"{i + 1}. **{label}**（{s.date_local} {period} {s.num_clips} clip / {s.duration_sec:.0f}s）")
    lines.append("")
    lines.append("→ 寫 cut-plan 時：")
    lines.append("- 每個 scene 配 1-2 caption（不要每個 clip 一張）")
    lines.append("- Day marker 放每個新日期第 1 scene 開頭")
    lines.append("- Location label 放每個 scene 開頭")
    lines.append("- ⛔ M9/M34: 寫 caption 前 Read 對應 grid 確認實拍內容")
    lines.append("- ☠️ M10: 任何數字 / 文化梗 / 歷史 facts 必 WebSearch 驗證")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


# ─────────────────────────────────────────────────────────────────────
# JSON report (machine-readable — build script ground truth)
# ─────────────────────────────────────────────────────────────────────

def write_json_report(
    audits: list[ClipAudit],
    scenes: list[Scene],
    output_path: Path,
    descriptions: dict[str, FrameDescription] = None,
) -> Path:
    """Write machine-readable JSON for build_capcut_draft.py / build_shorts.py to consume."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    descriptions = descriptions or {}

    data = {
        "version": 2,
        "schema": "silent_vlog_maker.audit v2 (R1 11d + M12 scene + M9 frame)",
        "summary": {
            "total_clips": len(audits),
            "total_duration_sec": sum(a.duration_sec for a in audits),
            "total_size_mb": sum(a.file_size_mb for a in audits),
            "scene_count": len(scenes),
            "gps_coverage": sum(1 for a in audits if a.has_gps),
            "dates": sorted({a.creation_date_local for a in audits if a.creation_date_local}),
        },
        "scenes": [
            {
                "scene_id": s.scene_id,
                "date_local": s.date_local,
                "period": s.period,
                "start_time": s.start_time_iso,
                "end_time": s.end_time_iso,
                "span_min": round(s.span_min, 1),
                "duration_sec": round(s.duration_sec, 1),
                "num_clips": s.num_clips,
                "center_lat": s.center_lat,
                "center_lng": s.center_lng,
                "location_label": s.location_label,
                "google_maps_url": s.google_maps_url,
                "filenames": s.filenames,
            }
            for s in scenes
        ],
        "clips": [
            {
                "filename": a.filename,
                "filepath": a.filepath,
                "file_size_mb": a.file_size_mb,
                "codec": a.codec,
                "width": a.width,
                "height": a.height,
                "fps": a.fps,
                "rotation": a.rotation,
                "color_transfer": a.color_transfer,
                "pix_fmt": a.pix_fmt,
                "is_hdr": a.is_hdr,
                "is_portrait": a.is_portrait,
                "duration_sec": a.duration_sec,
                "creation_time_real": a.creation_time_real,
                "creation_time_local": a.creation_time_local,
                "creation_time_natural": a.creation_time_natural,
                "creation_date_local": a.creation_date_local,
                "gps": {
                    "lat": a.gps_lat,
                    "lng": a.gps_lng,
                    "altitude": a.gps_altitude,
                    "accuracy_m": a.gps_accuracy_m,
                } if a.has_gps else None,
                "camera": {
                    "make": a.camera_make,
                    "model": a.camera_model,
                    "software": a.camera_software,
                },
                "audio": {
                    "codec": a.audio_codec,
                    "channels": a.audio_channels,
                    "sample_rate": a.audio_sample_rate,
                    "bitrate_kbps": a.audio_bitrate_kbps,
                } if a.audio_codec else None,
                "description": descriptions.get(a.filename).description if a.filename in descriptions else None,
                "key_elements": descriptions[a.filename].key_elements if a.filename in descriptions else [],
                "text_visible": descriptions[a.filename].text_visible if a.filename in descriptions else [],
            }
            for a in audits
        ],
    }

    output_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return output_path


# ─────────────────────────────────────────────────────────────────────
# One-shot: full audit → all reports
# ─────────────────────────────────────────────────────────────────────

def run_full_audit(
    raw_dir: Path,
    output_dir: Path,
    project_name: str = "Video Project",
    tz_offset_hours: int = 8,
    extract_frames: bool = True,
    cache_descriptions: bool = True,
) -> dict:
    """One-shot: audit + scene cluster + frame grids + reports.

    Returns: {
        "audits": list[ClipAudit],
        "scenes": list[Scene],
        "grid_paths": list[Path],
        "markdown_report": Path,
        "json_report": Path,
        "descriptions_cache": Path,
    }
    """
    from .audit import audit_raw_files, print_audit_report
    from .scene_audit import cluster_scenes, print_scene_timeline
    from .frame_audit import audit_all_clips_frames, load_descriptions

    output_dir.mkdir(parents=True, exist_ok=True)

    # Phase 1: R1 audit (11d)
    print(f"[Phase 1] R1 v2 audit on {raw_dir}...")
    audits = audit_raw_files(raw_dir, tz_offset_hours=tz_offset_hours)
    print_audit_report(audits)

    # Phase 2: scene clustering (M12)
    print(f"\n[Phase 2] M12 chronological + GPS scene clustering...")
    scenes = cluster_scenes(audits)
    print_scene_timeline(scenes)

    # Phase 3: hi-res frame extraction (M9/M34)
    grid_paths = []
    if extract_frames:
        print(f"\n[Phase 3] M9/M34 hi-res frame extraction (640×360 × 4 per clip)...")
        grid_paths = audit_all_clips_frames(audits, output_dir / "frame_audit")
        print(f"  Generated {len(grid_paths)} grid(s) at {output_dir / 'frame_audit'}")

    # Phase 4: load existing descriptions
    descriptions_cache = output_dir / "scene_descriptions.json"
    descriptions = load_descriptions(descriptions_cache) if cache_descriptions else {}

    # Phase 5: write reports
    print(f"\n[Phase 5] Writing reports...")
    md_path = write_markdown_report(audits, scenes, output_dir / "audit_report.md",
                                    descriptions=descriptions, grid_paths=grid_paths,
                                    project_name=project_name)
    json_path = write_json_report(audits, scenes, output_dir / "audit_report.json",
                                  descriptions=descriptions)
    print(f"  ✓ {md_path}")
    print(f"  ✓ {json_path}")
    print(f"  ✓ descriptions cache (load/save): {descriptions_cache}")

    return {
        "audits": audits,
        "scenes": scenes,
        "grid_paths": grid_paths,
        "markdown_report": md_path,
        "json_report": json_path,
        "descriptions_cache": descriptions_cache,
    }
